version: '3.4'

volumes: 
  datafiles: 

services:

  # MySQL
  db:
    container_name: mysql8
    image: mysql:8.0
    volumes:
      - '/var/lib/mysql'
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root

  lg.application:
    image: lgapplication:v2
    build:
      context: .  
      dockerfile: Api.Application/Dockerfile
    depends_on:
      - db
    ports:
        - "5000:80"
    restart: always
    environment: 
      - DBHOST=mysql8
  

